cmake .. \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
  -DENABLE_SIMMETRIX=ON \
  -DSIM_MPI=mpich3.3.2 \
  -DSIM_PARASOLID=OFF \
  -DCMAKE_CXX_COMPILER=g++ \
  -DCMAKE_C_COMPILER=gcc  \
  -DSKIP_SIMMETRIX_VERSION_CHECK=true